### ISSUE TITLE
Research - Python

### ISSUE THREAD

**Issue by treilly94** [scratch-map/scratch-map#3]
**Describe the solution you'd like**
Understand the pros/cons of developing this sort of app in python

**Describe alternatives you've considered**
React
Javascript

**Additional context**

**Comment by emilioward** [comment]
:snake: 

This is probably my strongest language in terms of knowledge and experience. We'd probably be looking to build the application in Flask or Django frameworks. Both are easy to setup but flask gives you more flexibility in terms of what database you want to choose etc. https://www.codementor.io/garethdwyer/flask-vs-django-why-flask-might-be-better-4xs7mdf8v

We'd probably look to implement a MVC (https://www.tutorialspoint.com/python_design_patterns/python_design_patterns_model_view_controller.htm) in python which is something me and @dcdarrell9 are familiar with but that probably the way i'd go forward. 

I guess it also depends what direction we want the app to be in are we looking to build a monolithic application or maybe develop a more micro-service architecture. This probably isn't the card to discuss this on and maybe we need to create one to talk about our architecture because then that can aid in deciding what language/ framework to use. 

This is a good flask tutorial - https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world

This is one I used to learn Django - https://docs.djangoproject.com/en/2.2/intro/tutorial01/

**Comment by dcdarrell9** [comment]
Basic Flask app created. We want to expand on this with some research into Python and it's functionality with certain APIs like different types of maps.
